### ISSUE TITLE
add support for  AD Service Principal client/secret

### ISSUE THREAD

**Issue by ehab2012** [duckdb/duckdb_azure#23]
hi

can you please add authentication support using  AD Service Principal client/secret.

basically it involves 3 items:

client_id
client_secret
tenant_id

adlfs  has good implementation https://raw.githubusercontent.com/fsspec/adlfs/main/adlfs/spec.py

I will buy you a coffee if this comes soon :)

Thank you and all the best
ehab

**Comment by ehab2012** [comment]
oh, i made this  before i checked
https://github.com/duckdb/duckdb_azure/issues/6

i will still buy you coffee thou :)

let me check first if it works.

**Comment by samansmink** [comment]
hey @ehab2012, closing this one in favor of the other issue, i will do my best for the coffee ;) it will depend on your definition of soon i think
