### ISSUE TITLE
Segfault with extension built on Ubuntu

### ISSUE THREAD

**Issue by kmatt** [duckdb/duckdb_azure#27]
The process below successfully builds the extension which INSTALLs from a local path, but on `LOAD azure`  the duckdb cli crashes.

Oddly this does not happen with the GitHub release binary, but testing a build on Ubuntu to address SSL CA errors: https://github.com/duckdb/duckdb_azure/issues/8#issuecomment-1847319222

```
$ duckdb -unsigned
v0.9.2 3c695d7ba9
Enter ".help" for usage hints.
D force install '/home/kmatt/source/duckdb_azure/build/release/extension/azure/azure.duckdb_extension';
D load azure;
Floating point exception (core dumped)

$ dmesg -T
[Fri Dec  8 18:31:53 2023] traps: duckdb[4008970] trap divide error ip:7f7cd3a3f275 sp:7ffc0a07f7e0 error:0 in azure.duckdb_extension[7f7cd350a000+1768000]
```

I'm not much on debugging C++, but building duckdb with debug to see if gdb shows anything helpful.

Build steps:

```
# Checkout source and submodule
git clone --recurse-submodules https://github.com/duckdb/duckdb_azure.git && cd duckdb_azure

# Install vcpkg in root of azure_duckdb source path
git clone https://github.com/Microsoft/vcpkg.git

# Run the bootstrap script to build vcpkg
vcpkg/bootstrap-vcpkg.sh

# Install dependencies
vcpkg/vcpkg install

# Make
VCPKG_TOOLCHAIN_PATH=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake make
```

**Comment by kmatt** [comment]
Oddly, a debug `duckdb` with the extension built with debug acts as if the extension is not loaded:

```
D install '/home/kmatt/source/duckdb_azure/build/debug/extension/azure/azure.duckdb_extension';
D load azure;
D select * from 'azure://test/data_*.json' limit 5;                                      

Error: Catalog Error: Table with name azure://test/data_*.json does not exist!           
Did you mean "sqlite_master"?
```

**Comment by samansmink** [comment]
@kmatt when building extensions for duckdb, the toolchain with which you compile should be the same or at least very similar to the ones used in duckdb's main binary distribution: check out https://github.com/duckdb/duckdb/blob/main/.github/config/distribution_matrix.json for the current distribution config. The workaround here is to also compile duckdb and any extensions you might need. For docs on building multiple extensions yourself easily, check out https://github.com/duckdb/duckdb/tree/main/extension. Note that this allows you to just statically link in all extensions you want and combine them in a single duckdb binary with the extensions pre-loaded.

**Comment by kmatt** [comment]
> @kmatt when building extensions for duckdb, the toolchain with which you compile should be the same or at least very similar to the ones used in duckdb's main binary distribution

In this case I'm building DuckDB for testing from the submodule the extension project uses, and in the same shell configured for azure_duckdb.

I will look the links you shared to see if I am missing some steps.
