### ISSUE TITLE
Connecting without connection string. 

### ISSUE THREAD

**Issue by mat-ej** [duckdb/duckdb_azure#28]
Hi DuckDB azure team, 

thanks for an amazing extension. 

I am running into an issue connecting, the problem is that my company does not allow connection strings to be revealed due to security reasons and their connector reads the relevant properties directly from $ az login system state in CLI. 

Can DuckDB azure do something similar ?

**Comment by samansmink** [comment]
hi @mat-ej check out https://github.com/duckdb/duckdb_azure/issues/6 on how to set up the pre-release with this feature. Next release of duckdb will be included with the azure extension with this feature.
