### ISSUE TITLE
Duck DB 0.10 seems to be broken

### ISSUE THREAD

**Issue by aersam** [duckdb/duckdb_azure#37]
Hi there

I had expected this to work according to docs in 0.10:

```python
import duckdb

with duckdb.connect() as con:
    con.execute(
        """INSTALL azure;
LOAD azure;
CREATE SECRET secret2 (
    TYPE AZURE,
    ACCOUNT_NAME 'account_name'
);"""
```
However, I get this: `duckdb.duckdb.InvalidInputException: Invalid Input Error: Secret type 'azure' not found`

**Comment by samansmink** [comment]
hi @aersam thanks for reporting! We've had some issue during release. I've just bumped the azure extension which should resolve the issue. Please reinstall using `FORCE INSTALL azure;`

**Comment by aersam** [comment]
Yeah, my CI/CD looks a lot better now, I think it's fixed :)

**Comment by samansmink** [comment]
Thanks for checking back, great to hear it works now!
