### ISSUE TITLE
MainDistributionPipeline build failed in main

### ISSUE THREAD

**Issue by quentingodeau** [duckdb/duckdb_azure#40]
Hello,

I saw that the [`MainDistributionPipeline`](https://github.com/duckdb/duckdb_azure/actions/workflows/MainDistributionPipeline.yml?query=branch%3Amain) didn't succeeded on windows with the main branch after my last PRs :(

 ```
azure-identity.lib(azure_cli_credential.cpp.obj) : error LNK2019: unresolved external symbol _Thrd_sleep_for referenced in function "void __cdecl std::this_thread::sleep_for<__int64,struct std::ratio<1,1000> >(class std::chrono::duration<__int64,struct std::ratio<1,1000> > const &)" (??$sleep_for@_JU?$ratio@$00$0DOI@@std@@@this_thread@std@@YAXAEBV?$duration@_JU?$ratio@$00$0DOI@@std@@@chrono@1@@Z) [D:\a\duckdb_azure\duckdb_azure\build\release\test\extension\loadable_extension_demo_loadable_extension.vcxproj]
```

Build [link](https://github.com/duckdb/duckdb_azure/actions/runs/7992417134/job/21825877793)

The issue itself is strange because the mentioned function is part of the STL...
I try to reproduce it on my computer but the build succeeded without any issue...

Do you have any idea or some input on the build (that is not show in the logs (i already check the version of the compiler, pythons...))

Also something is strange the build trigger on (PR#33)[51f680e314f17b351c3104dc1477362ac99d03dd ] & (PR#34)[74b2330df6a9bc91c9ff91e592dcce714f36f1be ] but not on (PR#35)[ec2cd30c0f894cbba089c1be454aa182b3e778c4] do you known why ?

Regards,
Quentin

**Comment by samansmink** [comment]
Hey @quentingodeau! 

Not sure what happened, i'm also seeing it on this totally unrelated pr in the aws extension https://github.com/duckdb/duckdb_aws/actions/runs/8003714877/job/21859620133?pr=32.

It appears like something changed in GH windows runner toolchain that makes the aws and azure sdk's now fail with this error

**Comment by chrono** [comment]
Hi @quentingodeau 

plz be aware that you're mentioning a few GitHub accounts in your quote. Please consider using code blocks for these situations.

```
azure-identity.lib(azure_cli_credential.cpp.obj) : error LNK2019: unresolved external symbol _Thrd_sleep_for referenced in function "void __cdecl std::this_thread::sleep_for<__int64,struct std::ratio<1,1000> >(class std::chrono::duration<__int64,struct std::ratio<1,1000> > const &)" (??$sleep_for@_JU?$ratio@$00$0DOI@@std@@@this_thread@std@@YAXAEBV?$duration@_JU?$ratio@$00$0DOI@@std@@@chrono@1@@z) [D:\a\duckdb_azure\duckdb_azure\build\release\test\extension\loadable_extension_demo_loadable_extension.vcxproj]
```

**Comment by quentingodeau** [comment]
@chrono Oh my bad I'm so sorry!!

**Comment by samansmink** [comment]
fixed by pinning a msvc version in the upstream workflow
