### ISSUE TITLE
Support of hierarchical namespace (dfs)

### ISSUE THREAD

**Issue by quentingodeau** [duckdb/duckdb_azure#43]
Hi @samansmink ,

This not really an issue but one of the feature I planning to work on.

I want to add the support of `dfs` endpoints to firstly improve the way that files are discovere when performing glob.

My idea is to add a new filesystem with a dedicated scheme (that have to be define).
But it can also be managed by simply choose over the endpoints, but I think it may be harder if we use this way because ms might have it own endpoints...

Do you have an opinion on this ?
Regards,
Quentin

**Comment by samansmink** [comment]
Hey @quentingodeau I'm not super familiar with the `dfs` endpoints, so please correct me if im wrong here.

Afaik these endpoints are for `Azure Data Lake Storage Gen2` which aims to add a file system layer on top of azure blob storage. This means that operations like globs would be more efficient through ADLS than through raw blob storage.

Assuming the files that are listed through ADLS are also accessible through raw blob urls, perhaps a nice 1st PR regarding this would be to:
- add support for adls url scheme
- add special glob handling for adls urls

Feel free to ping me by mail or discord for a chat!

**Comment by quentingodeau** [comment]
Yes exactly GEN2 is managing the paths with the notion of directories.
Yes that also true I can, in fact, as first approach managing only the listing of directories and keep the reading with the `blob` sdk they should be compatible in fact under the hood the datalake also use a [blob client](https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_service_client.hpp#L151).

Thx for the tips I didn't known that Duck had a discord I join it! Feel also free to ping me there even if I'm away or disconnected !

**Comment by quentingodeau** [comment]
Close has pr has been merged
