### ISSUE TITLE
Does this extension support other authetication ways such as service principal, or managed identity?

### ISSUE THREAD

**Issue by zczc2390** [duckdb/duckdb_azure#6]
Azure SDK provides several ways for client authentication. https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/identity/azure-identity/README.md
Could this extension support to authenticate client with methods other than connection string, such as service principal or managed identity, with settings from environment variables?

**Comment by timdenouden** [comment]
An example of Identity + The C++ Storage Client Library can be found here: https://learn.microsoft.com/en-us/azure/storage/blobs/quickstart-blobs-c-plus-plus?tabs=managed-identity%2Croles-azure-portal#sign-in-and-connect-your-app-code-to-azure-using-defaultazurecredential

**Comment by samansmink** [comment]
Thanks for the suggestion @zczc2390, this is definitely something we should look into! 👍  I think this should be pretty straightforward

**Comment by samansmink** [comment]
With PR #16, support was added for providing a credential chain. Its in a bit of an early shape but if you're on duckdb v0.9.1 you can try it out as follows:

Install nightly build of azure extension run from within DuckDB
```SQL
force install azure from 'http://duckdb-extensions-nightly.s3.us-east-2.amazonaws.com';
load azure;
set azure_account_name='<storage account name>';
set azure_credential_chain='cli';
from 'azure://<container>/path/to/file.ext';
```
The CLI credentials are tested and work well, but they only take. I think the environment variables should also work but they are not tested yet.

Note that to switch back to the default release of the azure extension, simply:
```
force install azure;
```

Will keep this issue open for now until the feature is working and properly tested with CI.

**Comment by jaroslaw-pawluszka** [comment]
Hi, I tried to use new duckDB feature of authentication to Azure using Service Principal via Jupyter Notebook (Python) and I failed. Thisis the code I run:. Can you advise if I am doing anything wrong or there is a bug?
```python
python import duckdb, os
# Define ENV variables to be used in authentication
os.environ['AZURE_TENANT_ID']='xxxxxxxxxxxxxxxxxxxxxx'
os.environ['AZURE_CLIENT_ID']= 'yyyyyyyyyyyyyyyyyyyyyy'
os.environ['AZURE_CLIENT_SECRET']= 'zzzzzzzzzzzzzzzzzzzzzzzzzz'
```
```python
con = duckdb.connect()
# install proper version of azure extension
con.execute("force install azure from 'http://nightly-extensions.duckdb.org';")
con.execute("load azure;")
# set config variables - my_account_name is of course replaced by real azure storage account name
set_string="SET azure_account_name = 'my_azure_account_name';"
con.execute(set_string)
# use service principal from ENV variables
set_string = "SET azure_credential_chain='env';"
con.execute(set_string)
# query ADLS gen 2
df = con.execute('''
    select *
    from 'azure://raw/test/troubleshoot/test_file.csv'
    ''')
```
I  got this error on the below line of code (query execution):

```python
df = con.execute('''
     select *
     from 'azure://raw/test/troubleshoot/test_file.csv'
    ''')
Error: Invalid Error: Failed to get token from ChainedTokenCredential.
```
I used Python 3.9.15 and the below version of duckdb package:
```
pip install duckdb==0.9.1
```

**Comment by samansmink** [comment]
hey @jaroslaw-pawluszka This is currently only available in the nightly build for 0.9.1 so you will need to run `force install azure from 'http://nightly-extensions.duckdb.org';` to install it

**Comment by jaroslaw-pawluszka** [comment]
Yes, Iam aware of that and this is what I used in the code I showed above (this is the line):
```python
con.execute("force install azure from 'http://nightly-extensions.duckdb.org';")
```

**Comment by jaroslaw-pawluszka** [comment]
Hi @samansmink  just to confirm that I am using proper nightly build I testes using the "old" azure extension: When I run the same code with default azure extension installation using:
```python
con.execute("force install azure;")
```
Then I get different error - it does not recognize "azure_account_name" parameter:
```python
CatalogException: Catalog Error: unrecognized configuration parameter "azure_account_name"
Did you mean: "username"
```
And it pops up on this line:
```python
set_string="SET azure_account_name = 'azuwevelcedls01p'"
---> con.execute(set_string)
```
So it makes me thing that this is the problem with the new nightly build, or I am not using it properly somehow.

**Comment by ehab2012** [comment]
i used above code and also get

`duckdb.duckdb.CatalogException: Catalog Error: unrecognized configuration parameter "azure_account_name"`

**Comment by samansmink** [comment]
@ehab2012  this is currently deployed as a nightly build, but not yet please try  `force install azure from 'http://nightly-extensions.duckdb.org';` in a few hours, I just merged the update and CI is still running which should push the nightly for 0.9.2

@jaroslaw-pawluszka sorry i misread your log. This appears to be a normal error message where the azure sdk could not find your credentials, are you sure the env settings are correct?

**Comment by ehab2012** [comment]
`
D force install azure from 'http://nightly-extensions.duckdb.org';
Error: HTTP Error: Failed to download extension "azure" at URL "http://nightly-extensions.duckdb.org/v0.9.2/linux_amd64_gcc4/azure.duckdb_extension.gz"
Extension "azure" is an existing extension.
`

my ~/.duckdb/extensions/v0.9.2/linux_amd64_gcc4

is empty.

![image](https://github.com/duckdb/duckdb_azure/assets/1481918/9040e28c-a904-4b9c-8870-30e03a6eb313)

how to over come is an existing extsnsion?

**Comment by ehab2012** [comment]
hello @samansmink i have tried to 

```
0.9.2 3c695d7ba9
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D force install azure from 'http://nightly-extensions.duckdb.org';
Error: HTTP Error: Failed to download extension "azure" at URL "http://nightly-extensions.duckdb.org/v0.9.2/linux_amd64_gcc4/azure.duckdb_extension.gz"
Extension "azure" is an existing extension.
```
can you please tell how/what to do so force will actually use the nightly build?

**Comment by jaroslaw-pawluszka** [comment]
Hi @samansmink ,

Happy New Year! :)
I am using the same credentials to connect to ADLS account using duckb and adlfs and it is working - so they look to be fine.
But as mentioned before, When I defined the env variables using the names as below and nightly build of azure and set_string = "SET azure_credential_chain='env';"
 ```python
python import duckdb, os
# Define ENV variables to be used in authentication
os.environ['AZURE_TENANT_ID']='xxxxxxxxxxxxxxxxxxxxxx'
os.environ['AZURE_CLIENT_ID']= 'yyyyyyyyyyyyyyyyyyyyyy'
os.environ['AZURE_CLIENT_SECRET']= 'zzzzzzzzzzzzzzzzzzzzzzzzzz'
```
Then I am getting this error: 
```python
duckdb.duckdb.Error: Invalid Error: Failed to get token from ChainedTokenCredential.
```
And I wanted to see if using the "azure" extension will result with better performance for getting the data from ADLS gen2.

**Comment by samansmink** [comment]
@Pedro-innocv @jaroslaw-pawluszka Sorry we haven't really had time to look into this yet, it's on the todo list though.

**Comment by quentingodeau** [comment]
@jaroslaw-pawluszka I think you are missing the 
```sql
SET azure_account_name = '<name of your storage account>';
```
I try to update the documentation page: https://duckdb.org/docs/extensions/azure.html
Tell me if after setting this property it work or not.
Also for information I'm working on a version where you will be able to define a spn secret directly.
Regards,
Quentin

**Comment by jaroslaw-pawluszka** [comment]
Hi @quentingodeau,

Actually I included storage account name in the code there - you can check my first message here (quoted below).
Please let me know if you have any updates.

Regards,
Jarek

> Hi, I tried to use new duckDB feature of authentication to Azure using Service Principal via Jupyter Notebook (Python) and I failed. Thisis the code I run:. Can you advise if I am doing anything wrong or there is a bug?
> 
> ```python
> python import duckdb, os
> # Define ENV variables to be used in authentication
> os.environ['AZURE_TENANT_ID']='xxxxxxxxxxxxxxxxxxxxxx'
> os.environ['AZURE_CLIENT_ID']= 'yyyyyyyyyyyyyyyyyyyyyy'
> os.environ['AZURE_CLIENT_SECRET']= 'zzzzzzzzzzzzzzzzzzzzzzzzzz'
> ```
> 
> ```python
> con = duckdb.connect()
> # install proper version of azure extension
> con.execute("force install azure from 'http://nightly-extensions.duckdb.org';")
> con.execute("load azure;")
> # set config variables - my_account_name is of course replaced by real azure storage account name
> set_string="SET azure_account_name = 'my_azure_account_name';"
> con.execute(set_string)
> # use service principal from ENV variables
> set_string = "SET azure_credential_chain='env';"
> con.execute(set_string)
> # query ADLS gen 2
> df = con.execute('''
>     select *
>     from 'azure://raw/test/troubleshoot/test_file.csv'
>     ''')
> ```
> 
> I got this error on the below line of code (query execution):
> 
> ```python
> df = con.execute('''
>      select *
>      from 'azure://raw/test/troubleshoot/test_file.csv'
>     ''')
> Error: Invalid Error: Failed to get token from ChainedTokenCredential.
> ```
> 
> I used Python 3.9.15 and the below version of duckdb package:
> 
> ```
> pip install duckdb==0.9.1
> ```

**Comment by Pedro-innocv** [comment]
Hi @jaroslaw-pawluszka, @quentingodeau 

I have tried setting the environment variables to upper case.

os.environ['AZURE_TENANT_ID'] = os.getenv('xxxxxxx')
os.environ['AZURE_CLIENT_ID'] = os.getenv('xxxxxxx')
os.environ['AZURE_CLIENT_SECRET'] = os.getenv('xxxxxxx')

I think the connection is now working, but I have a new error

![Screenshot 2024-02-02 at 10 17 35](https://github.com/duckdb/duckdb_azure/assets/72490447/3e298647-fd2f-4a22-89b5-c879ba6caad1)

seems that the connection is successful, because if I try with a non-existing route I get this other error
![Screenshot 2024-02-02 at 10 19 02](https://github.com/duckdb/duckdb_azure/assets/72490447/4d7339d9-04ca-44e0-a3f7-6cae74625845)

**Comment by quentingodeau** [comment]
Hi @jaroslaw-pawluszka 
Oh my bad I miss it!
the exception that you have is from the Azure SDK ([here](https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/identity/azure-identity/src/chained_token_credential.cpp#L137)). So let try to enable more logs^^ I see here that you may [have](https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/identity/azure-identity/src/chained_token_credential.cpp#L123) the real cause. Can you try to enable the logs to check a bit more [azure logs documentation](https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/core/azure-core#sdk-log-messages)

**Comment by quentingodeau** [comment]
Hi again I had make some tries at my end get the same issue than you @jaroslaw-pawluszka.

Here the logs i saw:
> [2024-02-03T18:51:58.7933982Z] WARN  : HTTP Transport error: Fail to get a new connection for: https://duckdbtest6.blob.core.windows.net. Problem with the SSL CA cert (path? access rights?)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.duckdb.Error: Invalid Error: Fail to get a new connection for: https://duckdbtest6.blob.core.windows.net. Problem with the SSL CA cert (path? access rights?)

my guess same error than: [here](https://github.com/duckdb/duckdb_azure/issues/8#issuecomment-1847319222)

After that it has been working like a charm :)

**Comment by quentingodeau** [comment]
Hi @Pedro-innocv, In your case I think that you have something different... and it might not be related to the azure extension but more on the parquet one, or to your parquet file. 
Are you able to read it with others tools like parquet-cli? 
Can you try on a other parquet file? does it work if download it and perform the same operation with the local file system?

**Comment by Pedro-innocv** [comment]
Hi @quentingodeau 
Tested directly with the parquet file locally and it works correctly.
We also tested with a new adls gen2 and everything works fine.
It seems that our customer has made some modifications to the adls gen2 configuration in production that cause these errors.
Thank you very much for everything

**Comment by jaroslaw-pawluszka** [comment]
Hi @quentingodeau ,

This one solved the issue! thanks :)

> Hi again I had make some tries at my end get the same issue than you @jaroslaw-pawluszka.
> 
> Here the logs i saw:
> 
> > [2024-02-03T18:51:58.7933982Z] WARN  : HTTP Transport error: Fail to get a new connection for: https://duckdbtest6.blob.core.windows.net. Problem with the SSL CA cert (path? access rights?)
> > Traceback (most recent call last):
> > File "", line 1, in 
> > duckdb.duckdb.Error: Invalid Error: Fail to get a new connection for: https://duckdbtest6.blob.core.windows.net. Problem with the SSL CA cert (path? access rights?)
> 
> my guess same error than: [here](https://github.com/duckdb/duckdb_azure/issues/8#issuecomment-1847319222)
> 
> After that it has been working like a charm :)

**Comment by samansmink** [comment]
Will close this issue, with v0.10.0 this is supported: https://duckdb.org/docs/extensions/azure#credential_chain-provider

testing can be improved a lot here still, please open a new issue if errors still arise.

**Comment by haj00007** [comment]
Using Duckdb 0.9.2 while connecting to adls gen2 to read parquet, its unable to connect while stmt.executy(query)
Gives 12002 connection timeout on network where proxy needed, if connected to others it works?
Any workaround.
Set proxy in system propety done, not working.
Any way to pass proxy to extension. Thanks.
