### ISSUE TITLE
How to get verbose logs?

### ISSUE THREAD

**Issue by mmaitre314** [duckdb/duckdb_azure#63]
Is it possible to get verbose logs from the DuckDB Azure extension? In particular logs which would show what happened during authentication?

I am hitting an auth error trying to query a blob in an Azure Storage Account. I am guessing my config is wrong, or maybe the Azure CLI auth failed for some reason, but the error message is not giving enough to root-cause the issue.

Notebook repro:
```
%sql duckdb:///:memory:

%sql CREATE SECRET azduckdb (TYPE AZURE, PROVIDER CREDENTIAL_CHAIN, SCOPE 'az://azduckdb.blob.core.windows.net/')

%sql SELECT count(*) FROM 'az://azduckdb.blob.core.windows.net/data/HuggingFaceFW/fineweb/CC-MAIN-2013-20/000_00000.parquet'

RuntimeError: (duckdb.duckdb.IOException) IO Error: AzureBlobStorageFileSystem open file 'az://azduckdb.blob.core.windows.net/data/HuggingFaceFW/fineweb/CC-MAIN-2013-20/000_00000.parquet' failed with code'',
Reason Phrase: 'Server failed to authenticate the request. Please refer to the information in the www-authenticate header.',
Message: ''
```
(in GitHub: https://github.com/mmaitre314/az-duckdb/blob/main/main.ipynb)

**Comment by quentingodeau** [comment]
Greetings, 

I think you can try with [AZURE_LOG_LEVEL](https://learn.microsoft.com/en-us/azure/developer/java/sdk/logging-overview#default-logger-for-temporary-debugging)

Regards,
Quentin

**Comment by mmaitre314** [comment]
Thanks! That did the trick. Somehow the logs were not getting displayed in VSCode Notebook but it worked running a plain py file. I'll see if I can expand the docs to mention logging.

For future reference:
```python
import os
import duckdb

os.environ['AZURE_LOG_LEVEL'] = 'verbose'

duckdb.sql("CREATE SECRET myaccount (TYPE AZURE, PROVIDER CREDENTIAL_CHAIN, SCOPE 'az://myaccount.blob.core.windows.net/')")
duckdb.sql("SELECT count(*) FROM 'az://myaccount.blob.core.windows.net/path/to/blob.parquet'")
```
