### ISSUE TITLE
Can't connect,  authentication errors with seemingly valid connection string

### ISSUE THREAD

**Issue by astrowonk** [duckdb/duckdb_azure#7]
I believe I have set a proper connection string with azure and loaded the extension in Duckdb 0.90.  The same connection string works with the AzureBlobFilesystem in python and authenticates and lists blobs, etc. 

But with duckdb on the command line the same connection string produces results like this:

``` 
Error: IO Error: AzureStorageFileSystem open file  <file path stuff> failed with Reason Phrase: Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
```

Is there a way to see this `www-authenticate` header?

**Comment by mrjsj** [comment]
I'm having similar issue, but with another error. Connecting to azure file storage through duckdb CLI produces the following error.
`Error: Invalid Error: Fail to get a new connection for: https://<CONTAINER_NAME>.blob.core.windows.net. Problem with the SSL CA cert (path? access rights?)`

Here's my snippet for duckdb CLI
```SQL
INSTALL azure;
LOAD azure;
SET azure_storage_connection_string = 'DefaultEndpointsProtocol=https;AccountName=<STORAGE_ACCOUNT_NAME>;AccountKey=<ACCOUNT_KEY>;EndpointSuffix=core.windows.net';
SELECT * FROM 'azure://<CONTAINER_NAME>/11112222-3333-4444-5555-666677778888.json';
```

and here's snippet for Python using the adlfs package:

```Python
import adlfs

CONNECTION_STRING = 'DefaultEndpointsProtocol=https;AccountName=<STORAGE_ACCOUNT_NAME>;AccountKey=<STORAGE_ACCOUNT_KEY>;EndpointSuffix=core.windows.net'
CONTAINER_NAME = '<CONTAINER_NAME>'

fs= adlfs.AzureBlobFileSystem(connection_string=CONNECTION_STRING)

with fs.open(f'{CONTAINER_NAME}/11112222-3333-4444-5555-666677778888.json', 'rb') as file:
	print(file.read())
```

**Comment by astrowonk** [comment]
> Currently not without debugger unfortunately. This error message is definitely something we should look into improving.
> 
> Also, I would love to take a look at why the token is not working, could you provide me with some info on how to reproduce this? Even easier, If you have a token that I can use to reproduce this, you can send it to me at `sam@duckdblabs.com`

I can reproduce the error in python and drop into the python debugger but not seeing what object or how I can view the www-authenticate header.

I can't share this particular SAS key or token... maybe I can get a free azure account personally and see if I can reproduce there after hours.

Does the SAS key in the connection-string need to be escaped? Again, the same `;` delimited connection string works in AzureBlobFileSystem but maybe the `-` char or something isn't playing nice with duckdb?

**Comment by quentingodeau** [comment]
Hi @mrjsj,
I got the same issue last week but I fix it by creating a symbolic link to the ca-certificates file. My guess is that when DuckDB is build it link with static libraries that expect the ca-certificates at a specific location but unfortunately this location depend on the Linux distribution...
Here the command that I had to run:
```sh
mkdir -p /etc/pki/tls/certs
ln -s /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt
```
Hopping that your issue is the same than me!
Regards,
Quentin

**Comment by aersam** [comment]
Did someone get this to work in an azure website?

**Comment by quentingodeau** [comment]
@aersam & @astrowonk it should be better now no ? with the dev version and with the [configuration](https://duckdb.org/docs/extensions/azure#configuration)

**Comment by quentingodeau** [comment]
> Did someone get this to work in an azure website?

what do you mean @aersam ?

**Comment by samansmink** [comment]
Thanks for checkin back @aersam, closing this issue for now, please open a new issue if problems persist!

**Comment by mattcln** [comment]
Hey,

I'm having the same issue, I've tried with 0.10.0 and 0.10.1.

```
duckdb.sql("install azure")
duckdb.sql("load azure")
duckdb.sql(f"set azure_storage_connection_string = '{conn_string}'")
query = f"""
    SELECT
        COUNT(*)
    FROM 'azure://scrapping-exports/exports/games.parquet'
"""
 duckdb.query(query)
```

I'm having this `Problem with the SSL CA cert (path? access rights?)` Exception. Am I missing something ?

Thank you !

**Comment by aersam** [comment]
Did you set azure_transport_option_type to curl?

**Comment by mattcln** [comment]
Ah you're right, it's working perfectly with `duckdb.sql(f"set azure_transport_option_type = 'curl'")`.

Thank you !

**Comment by mivade** [comment]
I was struggling with this until I found this issue. The suggestion to set `azure_transport_option_type` to `curl` resolved the issue, but it makes me wonder why considering it looks like libcurl is used by default. At the very least it would be nice to get this documented on the Azure extension docs page!

**Comment by quentingodeau** [comment]
but it is :)

![Image](https://github.com/user-attachments/assets/aa9e58b7-48f1-4e59-9660-47e3cd155909)

**Comment by afterthought** [comment]
The cli auth method fails for me when i set the transport to `curl`, FYI.

` CREATE SECRET (TYPE AZURE,
        PROVIDER credential_chain,
        ACCOUNT_NAME '<>',
        SCOPE '<>'
      )`
