### ISSUE TITLE
Querying abfss using the nightly  release crash duckdb

### ISSUE THREAD

**Issue by djouallah** [duckdb/duckdb_azure#74]
was trying to see if the new abfss format is working, instead it seems to crash duckdb

```
import duckdb
duckdb.sql(""" select * from 'abfss://xxxxxx@onelake.dfs.fabric.microsoft.com/NY.Lakehouse/Tables/ny/taxi/*.parquet' """)

```
when I use duckdb 1, i get a runtime error, which is expected but not a crash

**Comment by gdubya** [comment]
Strange... it works on my machine when I build from source (even from a Fabric table, surprisingly! I was expecting an error related to the endpoint). How is the nigthly build of duckdb put together with the nightly azure plugin? 

> 
> D select count(*) from read_parquet("abfss://REDACTED@onelake.dfs.fabric.microsoft.com/REDACTED/Tables/dbo/prices/*.parquet");
> ┌──────────────┐
> │ count_star() │
> │    int64     │
> ├──────────────┤
> │         3184 │
> └──────────────┘
> 
>

**Comment by djouallah** [comment]
all good, it was a transient issue, fixed with today nightly

**Comment by djouallah** [comment]
finally, @samansmink  where is my delta , really thank you all !!! 
<img width="829" alt="image" src="https://github.com/user-attachments/assets/f3147f29-90a6-4cc7-af54-dd07d6e9ed47">

**Comment by samansmink** [comment]
@djouallah delta is only built on the osx platform for nightly builds and has also been temporarily disabled for a bit as well, so it is missing for last night's nightly. OSX binaries should be built tonight or with the upcoming v1.1.0 release of DuckDB.

**Comment by djouallah** [comment]
@samansmink  just to be clear, delta will be available in the 1.1 right ?

**Comment by samansmink** [comment]
@djouallah yea for sure!

**Comment by djouallah** [comment]
thank you i nearly had a heart attack :)
