### ISSUE TITLE
Performance Issue: Slow Query Execution Against Parquet File on Azure Blob Storage

### ISSUE THREAD

**Issue by snavarropino** [duckdb/duckdb_azure#89]
I'm experiencing a significant performance issue when querying a Parquet file (approx. 4 GB) stored in Azure Blob Storage using the DuckDB Azure extension. Here's a summary of my setup and the observed differences in execution times:
File and Storage Information:

    File Size: ~4 GB
    Storage Account Type: StorageV2 (general purpose v2) with Hierarchical Namespace enabled
    Connection: abfs://container/blob

## Performance Comparison:

Querying Locally:
- I downloaded the blob to my local machine and queried it directly with DuckDB.
- Execution Time: Approximately 68 seconds.
- Network Bandwidth: My local download maxes out at my full available bandwidth (500 Mbps).

Querying via Azure Extension:
- When I use the DuckDB Azure extension to query the file directly on Azure Blob Storage (abfs://storage.container.blob), the execution time is significantly slower.
- Execution Time: Approximately 255 seconds.
- Observed Network Bandwidth: The extension seems to utilize only around 80-100 Mbps, even though my connection allows up to 500 Mbps.

## Expected Behavior:

It would be expected that querying a file in Azure Blob Storage directly via the extension would have comparable performance to querying locally, especially considering network capabilities.

Any guidance on potential workarounds or optimizations would be appreciated.

**Comment by samansmink** [comment]
You could try to increase the threads used by DuckDB, that could make a difference since DuckDB does not currently use async io.

Also, how many rowgroups are there in this parquet file? DuckDB paralellizes parquet scans by distributing the row groups to be scanned across the threads.

**Comment by snavarropino** [comment]
Thank you for the prompt response.

Yes, I have experimented with modifying the number of threads, as well as adjusting the buffer and chunk sizes following the recommendations in the documentation ([link to configuration settings](https://duckdb.org/docs/extensions/azure.html#configuration)). Unfortunately, these adjustments did not yield any noticeable improvements in performance.

For example, this confoguration didn't improve at all:

```cmd
SET azure_read_transfer_concurrency = 20;
SET azure_read_transfer_chunk_size = 4_194_304;
SET azure_read_buffer_size = 8_388_608;
SET azure_transport_option_type = curl;

SELECT * FROM 'abfs://container/blob' 
               WHERE PointOfSaleId = '6'
```
I’ll also investigate the suggestion regarding row groups and will update this issue with any relevant findings.

Thank you for your help.

**Comment by samansmink** [comment]
Thanks @snavarropino! I have not yet had a deep look into abfs performance, so any findings you have are super useful

**Comment by snavarropino** [comment]
Finally I managed to configure the propper settings to use my full bandwidth by adjusting the number of threads.

```
SET azure_transport_option_type = curl;
SET threads = 15;
SELECT * FROM 'abfs://container/blob' 
               WHERE PointOfSaleId = '6'
```
The other settings (buffer, chunk, etc...) don't affect the performance I observe

**Comment by samansmink** [comment]
Cool! I'm going to close this issue now. Note that increasing the threads for network performance is documented here https://duckdb.org/docs/guides/performance/how_to_tune_workloads#querying-remote-files
